perf(btoa): improve btoa() speed
davidchambers/Base64.js pull request #55
Opened 2023-01-12 01:20 UTC by sno2

This utilizes more performant methods to generate the string. The only thing I didn't keep from Dumitru's initial proof-of-concept (See #23) was a few changes to make it spec-compliant and the array-based accumulator for the chunks. It turns out JavaScript engines optimize rope strings far better which makes it more performant to use string concatenation.

Here are the benchmarks (btoa before is the current version, btoa after is Dumitru's concept, btoa live is this PR):

50 characters:

```
benchmark        time (avg)             (min … max)       p75       p99      p995
--------------------------------------------------- -----------------------------
btoa before   38.51 µs/iter    (30.3 µs … 303.3 µs)   37.8 µs  114.8 µs  142.2 µs
btoa after     25.3 µs/iter      (18 µs … 396.6 µs)   25.2 µs   64.2 µs  112.5 µs
btoa live        22 µs/iter    (15.3 µs … 386.5 µs)   21.4 µs   53.3 µs  126.7 µs
```

1,000 characters:

```
benchmark        time (avg)             (min … max)       p75       p99      p995
--------------------------------------------------- -----------------------------
btoa before  778.92 µs/iter    (622.2 µs … 2.49 ms)  813.3 µs   1.51 ms   1.95 ms
btoa after   503.36 µs/iter    (340.6 µs … 1.53 ms)  588.4 µs   1.15 ms    1.2 ms
btoa live    411.27 µs/iter      (287 µs … 1.34 ms)  421.9 µs  935.6 µs   1.07 ms
```

10,000 characters:

```
benchmark        time (avg)             (min … max)       p75       p99      p995
--------------------------------------------------- -----------------------------
btoa before    9.86 ms/iter    (6.65 ms … 39.19 ms)  12.39 ms  39.19 ms  39.19 ms
btoa after     4.86 ms/iter      (4.3 ms … 10.2 ms)   4.69 ms   7.93 ms   10.2 ms
btoa live      3.69 ms/iter     (3.17 ms … 7.08 ms)   3.58 ms   6.74 ms   7.08 ms
```

Co-authored-by: Dumitru Uzun <contact@duzun.me>

2023-02-09 15:40 UTC, davidchambers requested changes
Thank you for your pull request, @sno2!

I'd like to discuss a few changes:

  - I noticed a few places where the code style is not consistent with the existing code. When I investigated this I discovered a bug I introduced that prevented the linter from flagging the inconsistencies. I fixed the bug in #56. Please rebase your branch and run `make lint` to see the inconsistencies. :)

  - I see the word hexet in your comments, but I cannot find such a word (in English, at least). Do you mean [hextet][1]?

  - We could use `while (i < data.length) { … }` rather than `do { … } while (i < data.length);`. It uses the simpler language feature, and would obviate the need for the `!data.length` guard.

  - I think the following code could be rewritten to improve readability:

    ```javascript
    return (r ? acc.slice(0, r - 3) : acc) + "===".slice(r || 3);
    ```

    I don't like checking for the `0` case twice (and relying on type coercion). I'd prefer to check for `0` just once, explicitly:

    ```javascript
    return r === 0 ? acc : acc.slice(0, r - 3) + '==='.slice(r);
    ```

    Since `r` has only two possible values in the alternative branch, I suggest handling each of the three cases individually:

    ```javascript
    switch (data.length % 3) {
      case 0: return acc;
      case 1: return acc.slice(0, -2) + '==';
      case 2: return acc.slice(0, -1) + '=';
    }
    ```

    I find this clearer than the current approach. What do you think?


[1]: https://en.wikipedia.org/wiki/Hextet

2023-02-12 15:12 UTC, sno2 commented
Hello @davidchambers , I agreed with your suggested changes and have made amends to the code.

2023-02-22 12:22 UTC, davidchambers approved these changes

2023-02-22 12:24 UTC, davidchambers commented
Thanks for making the changes, @sno2! I pushed a few formatting changes. Let me know whether you're happy with them. :)

2023-02-22 14:29 UTC, sno2 commented
The formatting changes LGTM, thanks

2023-02-22 16:02 UTC, merged